# config.yml default template
# node:
#   default: default_value
#   advice:
#     - value1
#     - value2
#     - value3
#   comment:
#     - "This is comment line 1."
#     - "This is comment line 2."
#   type: string
#   force_advice: true # if type is a string
#   range: "[0,+∞)" # if type is a number

data.datasource:
  default: "mysql"
  advice: [ "mysql" ]
  type: string
  force_advice: true
  range:

data.prefix:
  default: "ag_"
  advice: [ "log_", "prism_" ]
  type: string
  force_advice: false
  range:

data.mysql.hostname:
  default: "127.0.0.1"
  advice: [ "127.0.0.1", "localhost" ]
  type: string
  force_advice: false
  range:

data.mysql.port:
  default: 3306
  advice: [ ]

  type: int
  force_advice: false
  range: "(0, 65535)"

data.mysql.username:
  default: "root"
  advice: [ ]
  type: string
  force_advice: false
  range:

data.mysql.password:
  default: "root"
  advice: [ ]
  type: string
  force_advice: false
  range:

data.mysql.database:
  default: "minecraft"
  advice: [ ]
  type: string
  force_advice: false
  range:

data.advance.max-failures-before-wait:
  default: 5
  advice: [ ]
  type: int
  force_advice: false
  range:

data.advance.actions-per-insert-batch:
  default: 300
  advice: [ ]
  type: int
  force_advice: false
  range:

data.advance.force-write-queue-on-shutdown:
  default: true
  advice: [ ]
  type: boolean
  force_advice: false
  range:
